version: "3.9"
services:
    client:
        image: siraphopdocker/ebook-frontend
        container_name: client
        ports:
            - "443:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true

    redis:
        image: redis:alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        container_name: redis
        ports:
            - 6379:6379
        volumes: 
            - ./redis-vol:/data

    user:
        image: siraphopdocker/ebook-user
        container_name: user
        depends_on:
            - redis
        env_file: 
            ./user/user.env
        ports:
            - 8000:8000
        environment:
            - APP_PORT=${APP_PORT}
            - DB_DB_URI=${DB_DB_URI}
            - DB_CLDNAME=${DB_CLDNAME}
            - DB_CLDAPI=${DB_CLDAPI}
            - DB_CLDSECRET=${DB_CLDSECRET}
            - TOKEN_ACCESS_TOKEN=${TOKEN_ACCESS_TOKEN}
            - TOKEN_REFRESH_TOKEN=${TOKEN_REFRESH_TOKEN}
            - REDIS_DSN=${REDIS_DSN}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - ESB_URI=${ESB_URI}
    
    book:
        image: siraphopdocker/ebook-book
        container_name: book
        env_file: 
            ./book/book.env
        ports:
            - 8001:8000
        environment: 
            - APP_PORT=${APP_PORT}
            - DB_DB_URI=${DB_DB_URI}
            - DB_CLDNAME=${DB_CLDNAME}
            - DB_CLDAPI=${DB_CLDAPI}
            - DB_CLDSECRET=${DB_CLDSECRET}
            - AUTH_URI_BOOK=${AUTH_URI_BOOK}
            - ESB_URI=${ESB_URI}
    
    cart:
        image: siraphopdocker/ebook-cart
        container_name: cart
        env_file: 
            ./cart/cart.env
        ports:
            - 8002:8000
        environment:
            - APP_PORT=${APP_PORT}
            - DB_DB_URI=${DB_DB_URI}
            - AUTH_URI_CART=${AUTH_URI_CART}
            - ESB_URI=${ESB_URI}


