version: "3.9"
services:
    nginx:
        # image: siraphopdocker/ebook-nginx
        build:
            context: ./nginx
        restart: always
        container_name: nginx
        ports:
            - 8080:80

    client:
        # image: siraphopdocker/ebook-frontend
        build:
            context: ./frontend
        container_name: client
        ports:
            - 3000:3000

    redis:
        image: redis:alpine
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        container_name: redis
        ports:
            - 6379:6379
        volumes: 
            - ./redis-vol:/data

    user:
        # image: siraphopdocker/ebook-user
        build:
            context: ./user
        container_name: user
        depends_on:
            - redis
        env_file: 
            ./user/user.env
        ports:
            - 8000:8000
    
    books:
        # image: siraphopdocker/ebook-book
        build:
            context: ./book
        container_name: book
        env_file: 
            ./book/book.env
        ports:
            - 8001:8001
    
    cart:
        # image: siraphopdocker/ebook-cart
        build:
            context: ./cart
        container_name: cart
        env_file: 
            ./cart/cart.env
        ports:
            - 8002:8002